# Generated by Django 2.1.1 on 2018-12-12 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='')),
                ('text', models.TextField(max_length=500)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 12, 12, 10, 38, 5, 23066))),
                ('source', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
