# Generated by Django 2.1.1 on 2018-12-16 10:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contentapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 12, 16, 10, 24, 21, 988036, tzinfo=utc), verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=500, verbose_name='Основной текст')),
            ],
        ),
        migrations.AlterField(
            model_name='new',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 10, 24, 21, 987225, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='new',
            name='source',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='new',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
    ]
