# Generated by Django 2.1.1 on 2018-12-16 11:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contentapi', '0002_auto_20181216_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ['pub_date']},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['pub_date']},
        ),
        migrations.AddField(
            model_name='information',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 11, 0, 5, 90723, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 11, 0, 5, 90189, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 11, 0, 5, 89312, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
