# Generated by Django 2.1.1 on 2018-12-16 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contentapi', '0003_auto_20181216_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='text',
            field=models.CharField(max_length=500, null=True, verbose_name='Вспомагательный текст'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 14, 39, 53, 751791, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='information',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 14, 39, 53, 752372, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 14, 39, 53, 750972, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
