# Generated by Django 2.1.1 on 2019-01-06 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contentapi', '0004_auto_20181216_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50, verbose_name='Автор')),
                ('text', models.TextField(max_length=300, verbose_name='Текст комментария')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 1, 6, 15, 54, 45, 446727, tzinfo=utc), verbose_name='Дата публикации')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 6, 15, 54, 45, 445169, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.CharField(max_length=50, null=True, verbose_name='Вспомагательный текст'),
        ),
        migrations.AlterField(
            model_name='information',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 6, 15, 54, 45, 445820, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 6, 15, 54, 45, 444225, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='comment',
            name='this_new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contentapi.New'),
        ),
    ]
