# Generated by Django 2.1.1 on 2019-01-08 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contentapi', '0005_auto_20190106_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Альбом')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 1, 8, 12, 22, 56, 889757, tzinfo=utc), verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('albom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentapi.Albom', verbose_name='Фото')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 12, 22, 56, 888245, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 12, 22, 56, 885703, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='information',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 12, 22, 56, 887207, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 12, 22, 56, 884713, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
